version: "1.0"
project:
  name: bodywork-ml-dashboard-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1_train_model >> stage_2_dashboard_app
stages:
  stage_1_train_model:
    executable_module_path: stage_1_train_model/train_model.py
    requirements:
      - boto3==1.16.15
      - joblib==0.17.0
      - pandas==1.1.4
      - scikit-learn==0.23.2
    cpu_request: 0.5
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
  stage_2_dashboard_app:
    executable_module_path: stage_2_dashboard_app/run_app.py
    requirements:
      - dash==1.19.0
      - dash-auth==1.4.1
      - dash-bootstrap-components==0.11.3
      - joblib==0.17.0
      - numpy==1.19.5
      - pandas==1.1.4
      - scikit-learn==0.24.1
      - statsmodels==0.12.2
    secrets:
      DASH_USERNAME: plotly-dash-credentials
      DASH_PASSWORD: plotly-dash-credentials
    cpu_request: 0.5
    memory_request_mb: 200
    service:
      max_startup_time_seconds: 30
      replicas: 2
      port: 8050
      ingress: true
logging:
  log_level: INFO
