version: "1.1"
project:
  name: bodywork-ml-dashboard-project
  docker_image: bodyworkml/bodywork-core:3.0
  DAG: stage_1_train_model >> stage_2_dashboard_app
  secrets_group: dev
stages:
  stage_1_train_model:
    executable_module_path: train_model.py
    requirements:
      - boto3==1.24.13
      - pandas==1.4.2
      - joblib==1.1.0
      - scikit-learn==1.1.0
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 180
      retries: 2
  stage_2_dashboard_app:
    executable_module_path: run_app.py
    requirements:
      - dash==2.5.1
      - dash-auth==1.4.1
      - dash-bootstrap-components==1.1.0
      - joblib==1.1.0
      - numpy==1.22.4
      - pandas==1.4.2
      - scikit-learn==1.1.0
      - statsmodels==0.13.2
    secrets:
      DASH_USERNAME: plotly-dash-credentials
      DASH_PASSWORD: plotly-dash-credentials
    cpu_request: 0.5
    memory_request_mb: 250
    service:
      max_startup_time_seconds: 180
      replicas: 2
      port: 8050
      ingress: true
logging:
  log_level: INFO
